### ISSUE TITLE
Quick bugfix for `Compiler Version` replacement - remove space

### ISSUE THREAD

**Issue by plotchy** [naddison36/sol2uml#106]
Noticed a minor issue after testing the new feature. It is creating invalid syntax, ex:
`pragma solidity = 0.8.4;`

I believe the space after `=` should be removed here:
https://github.com/naddison36/sol2uml/blob/a31033ed05a2d8502dfcb901ede95065af08db55/src/ts/parserEtherscan.ts#L157
```
let solidityCode = `pragma solidity =${solidityVersion};\n`
```

**Comment by plotchy** [comment]
I did a quick runthrough of your PR after seeing this behavior. I'm not familiar with TS so I could be missing the correct location for where this should be adjusted.

**Comment by naddison36** [comment]
Sorry about that. I should have picked that up when I tested. Try v2.2.3
