### ISSUE TITLE
Strictly speaking, "< 1024" and "not larger than 1024" are not equivalent.

### ISSUE THREAD

**Issue by mikel-misha** [naddison36/sol2uml#137]
Strictly speaking, "< 1024" and "not larger than 1024" are not equivalent.

```suggestion
1. Check that the <code>[=credentialId=]</code> is &le; 1023 bytes. Credential IDs larger than this many bytes SHOULD cause the RP to fail this [=registration ceremony=].
```

And if I may (this is more subjective), I think it's worth eliminating the little indirection here. Not that it's a lot of cognitive load, but every bit helps.

```suggestion
1. Check that the <code>[=credentialId=]</code> is &le; 1023 bytes long. Credential IDs larger than 1023 bytes SHOULD cause the RP to fail this [=registration ceremony=].
```

_Originally posted by @emlun in https://github.com/w3c/webauthn/pull/1664#discussion_r713335901_

**Comment by naddison36** [comment]
more spam

**Comment by mikel-misha** [comment]
> more spam
