### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by mikel-misha** [naddison36/sol2uml#138]
### Why:

Closes #23524 
To fix missing information that is not present in the docs, but present in the in-file form schema editor:
![Screenshot 2023-01-27 at 13 33 36](https://user-images.githubusercontent.com/32039051/215092016-521b9f60-64ba-485a-ad75-9de5354fe5c6.png)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Adds the `Only for public repositories` text on each required key.
![Screenshot 2023-01-27 at 13 53 28](https://user-images.githubusercontent.com/32039051/215091770-c40d18a0-f7d1-4a28-aa6f-6db9d7517221.png)

To align with the github in-file editor documentation: 
![Screenshot 2023-01-27 at 13 33 36](https://user-images.githubusercontent.com/32039051/215091820-611f3f77-7324-4c54-a358-796c0a4378c8.png)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

_Originally posted by @MagnusHJensen in https://github.com/github/docs/pull/23525_

**Comment by naddison36** [comment]
spam
