### ISSUE TITLE
Output format argument 'all' does not produce dot file

### ISSUE THREAD

**Issue by sambacha** [naddison36/sol2uml#154]
running 

```bash
sol2uml class ./contracts/ -f all -v
```

only gives a png and svg file. 

```bash
 sol2uml class ./contracts/ -f dot -v
```

the logs show that:

```console
sol2uml About to write Dot file to /Users/janitor/mev-proxy/classDiagram.svg +0ms
sol2uml About to convert dot to SVG +0ms
sol2uml About to write SVN file to /Users/janitor/mev-proxy/classDiagram.svg +62ms
```

> Additionally SVN I think is meant to be SVG?

while running explicitly 

```console
sol2uml About to write Dot file to /Users/janitor/mev-proxy/classDiagram.dot +0ms
sol2uml Finished generating UML +143ms
Dot file written to /Users/janitor/mev-proxy/classDiagram.dot
```

Also I think the parser may not be able to handle comments with emojis, but that is a separate issue potentially not sure yet if that is the issue I had earlier

**Comment by naddison36** [comment]
Thanks for reporting. This should be fixed in https://github.com/naddison36/sol2uml/releases/tag/v2.5.10
