### ISSUE TITLE
sol2uml diff: enable diffing contracts between chains

### ISSUE THREAD

**Issue by 0xmichalis** [naddison36/sol2uml#160]
Doing something like the following:
```
sol2uml diff --networka matic --networkb celo <addressa> <addressb>
```

**Comment by naddison36** [comment]
this is a good idea. I'll see what I can do

**Comment by naddison36** [comment]
I added support for this in release [v2.5.7](https://github.com/naddison36/sol2uml/releases/tag/v2.5.7)

**Comment by 0xmichalis** [comment]
Amazing, thanks @naddison36!
