### ISSUE TITLE
FR: ignore storage slots matching a pattern

### ISSUE THREAD

**Issue by aspiers** [naddison36/sol2uml#161]
Here's an example of a contract ([`0x8A4d...09DD` on Polygon](https://polygonscan.com/address/0x8A4d7458dDe3023A3B24225D62087701A88b09DD)) which due to its upgradeability (via OpenZeppelin) has [various gaps deliberately inserted in the storage layout](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#storage-gaps):

![CarbonOffsetBatches](https://github.com/naddison36/sol2uml/assets/100738/8f561c29-3004-4bc1-af44-6a0017a22a40)

These `__gap` structures will never contain data, so it would be great if there was an option to exclude them from the generated diagram.

**Comment by naddison36** [comment]
That's a good idea. I'll see what I can do. Maybe have an option which is a comma-separated list of variable names to ignore expanding out.

**Comment by aspiers** [comment]
Yes that sounds perfect, thanks a lot!

**Comment by naddison36** [comment]
I've added support for this in release [v2.5.9](https://github.com/naddison36/sol2uml/releases/tag/v2.5.9)

Here's the result using your example
```
sol2uml storage 0xa90dAF1975BA13c26F63976e0Fd73A21F966EE0D --hideExpand __gap --network polygon -v
```

![CarbonOffsetBatches](https://github.com/naddison36/sol2uml/assets/6491112/5c8a4e4b-fae4-4db9-89c7-207c87c2ad6e)

**Comment by aspiers** [comment]
Awesome, thanks so much!
