### ISSUE TITLE
Support for abstract contracts in Solidity 0.6

### ISSUE THREAD

**Issue by naddison36** [naddison36/sol2uml#18]
Unfortunately, the dependant Solidity parser [solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr) does not currently handle the new `abstract` keyword for contracts.

Issue [104](https://github.com/federicobond/solidity-parser-antlr/issues/104) has been raised with solidity-parser-antlr

An example Solidity 0.6 contract with abstract contracts is [0x92d861ebf39661f22eaae05fedcbf31989b17e45](https://etherscan.io/address/0x92d861ebf39661f22eaae05fedcbf31989b17e45#code)

**Comment by ljs123-bit** [comment]
​
​
-----Original Message-----

**Comment by naddison36** [comment]
I've forked [solidity-antlr4](https://github.com/naddison36/solidity-antlr4) and [solidity-parser-antlr](https://github.com/naddison36/solidity-parser-antlr) to fix this issue.
Once PRs https://github.com/ConsenSys/solidity-antlr4/pull/5 and https://github.com/ConsenSys/solidity-parser-antlr/pull/17 on the dependant packages have been merged, I'll change back to ConsenSys' [solidity-parser-antlr](https://github.com/ConsenSys/solidity-parser-antlr) package.

**Comment by ljs123-bit** [comment]
I'm not sure what that means, can you explain it? 
Did you make AECT? 
Is this coin a safe coin?I would like to request information about AECT Coins. I'm curious about the company that made it

Please contact us by personal contact information,LINE ID : posuckwechat ID : posuck
Please tell me your personal message ID.
I'm not sure what that means, can you explain it,
