### ISSUE TITLE
UML generation incorrect when Contracts with same names in different folders with relative imports are used

### ISSUE THREAD

**Issue by Shirikatsu** [naddison36/sol2uml#21]
# Problem

If the set of folders that are being used to generate the UML contain contracts with the same name but are subsequently imported differently as dictated by their relative imports, the generated UML shows that all contracts that inherit a contract with such a name all inherit from the same contract.

# Reproduction

## Set up

Create a folder set up as below:

```bash
uml
 ├── 1
 │   ├── Parent.sol
 │   └── sub
 │        └── Child.sol
 └── 2
     ├── Parent.sol
     └── sub
          └── Child.sol
```

The contracts themselves can contain anything --- they can be the same code or completely different, the result is unchanged.

For this example we just used blank contracts:

`Parent.sol`:
```solidity
pragma solidity ^0.6.2;

contract Parent {
}
```

`Child.sol`
```solidity
pragma solidity ^0.6.2;

import "../Parent.sol";

contract Child is Parent {

}
```

Note the relative import in `Child.sol`. This means that each Child inherits specifically from the Parent in the parent folder and nowhere else. `solc` compiles the contracts in this way.

## Command

Now run `sol2uml uml/ -f png` to get:

![issue](https://user-images.githubusercontent.com/4716816/101353447-7c2f0d00-388b-11eb-9d5b-678372179a08.png)

As shown, even when both Children do not inherit from the same Parent, the generated UML reports that they do.

# Additional Notes

If the offending contracts have different/same file names, the problem does not change.

If the offending contracts have different contract names, the problem goes away regardless of file name:

![changed](https://user-images.githubusercontent.com/4716816/101353834-2ad34d80-388c-11eb-924a-49023844def4.png)

What we expect is the above image to be generated with the contract names staying the same.

**Comment by naddison36** [comment]
Thanks for reporting this issue with clear reproduction instructions.

This is a tricky one which is why it wasn't handled in the earlier versions. I've managed to work out a solution so please give the latest version `1.1.21` a try.

**Comment by Shirikatsu** [comment]
Thanks for the amazing turnaround time! It works perfectly. Great job @naddison36 !
