### ISSUE TITLE
Fails to parse pragma solidity ^0.5;

### ISSUE THREAD

**Issue by ferittuncer** [naddison36/sol2uml#3]
If we omit patch number, it fails to parse.

So,

this works: `pragma solidity ^0.5.7;`

but this doesn't: `pragma solidity ^0.5;`

**Comment by naddison36** [comment]
This is an issue with the dependent [solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr) library
https://github.com/federicobond/solidity-parser-antlr/issues/15

**Comment by asaharinna** [comment]
😂

**Comment by naddison36** [comment]
I've finally fixed this issue by forking the dependant libraries.
Once PRs https://github.com/ConsenSys/solidity-antlr4/pull/5 and https://github.com/ConsenSys/solidity-parser-antlr/pull/17 on the dependant packages have been merged, I'll change back to ConsenSys' [solidity-parser-antlr](https://github.com/ConsenSys/solidity-parser-antlr) package.
