### ISSUE TITLE
Relationship with SOLIDITY 2 UML 

### ISSUE THREAD

**Issue by flipNFTs** [naddison36/sol2uml#30]
Hi there, what's the relationship between your package sol2uml and the solidity plug-in  SOLIDITY 2 UML?

**Comment by naddison36** [comment]
I don't know. Do you have a link to solidity plug-in SOLIDITY 2 UML? What's it a plug-in for?

**Comment by flipNFTs** [comment]
For a given smart contract in Remix IDE, the plug-in can give me a graph like this. Not exactly sure if I was doing it right. Hence googling to find confirmations.

![image](https://user-images.githubusercontent.com/83438620/117245979-56278c00-ae6e-11eb-93a0-063b21f182f0.png)

**Comment by naddison36** [comment]
That looks like sol2uml output so I'd say the Remix IDE plug-in is using sol2uml

**Comment by naddison36** [comment]
Here's the proposal to add sol2uml as plug-in to Remix https://github.com/Machinalabs/remix-plugin-proposals/issues/4
I've haven't found where the source code for the plug-in is yet

**Comment by flipNFTs** [comment]
This could go big as the complexity of DApp smart contracts is getting higher.

**Comment by naddison36** [comment]
Yes, it can get very big. That's why sol2uml has some options to filter stuff out. eg
```
  -b, --baseContractNames <value>              only output contracts connected to these comma separated base contract names
  -d, --depthLimit <depth>                     number of sub folders that will be recursively searched for Solidity files. Default -1 is unlimited (default: -1)
  -a, --hideAttributes                         hide class and interface attributes
  -p, --hideOperators                          hide class and interface operators/functions
  -e, --hideEnums                              hide enum types
  -s, --hideStructs                            hide data structures
  -l, --hideLibraries                          hide libraries
  -t, --hideInterfaces                         hide interfaces
```
