### ISSUE TITLE
New feature to generate documentation using the NatSpec in contract source code

### ISSUE THREAD

**Issue by naddison36** [naddison36/sol2uml#31]
sol2uml already has the logic to pull the verified source code for a contract from Etherscan or get the source code from the local filesystem. This can be used to then generate contract documentation using a Solidity document generator like [solidity-docgen](https://github.com/OpenZeppelin/solidity-docgen).

A new option would be used to do this.
`-g, --genDocs`

Will also need an option to specify the folder the HTML files should be written to.

**Comment by BigBlueHundids** [comment]
>.

**Comment by naddison36** [comment]
other tools do this so closing
