### ISSUE TITLE
Does it work on the remix platform?

### ISSUE THREAD

**Issue by JesusRosaB** [naddison36/sol2uml#47]
I am using the remix platform for my smart contracts in solidity and when I activate the sol2uml plugin it does not activate, is there an error? can you help me? thank you very much.

**Comment by m14253647g** [comment]
Bsc

**Comment by naddison36** [comment]
I didn't do the Remix plugin for sol2uml so I can't help much. Best to raise an issue in https://github.com/aquiladev/remix-sol2uml

**Comment by kingwill3** [comment]
``
