### ISSUE TITLE
Generating all Open Zeppelin contracts with the `--clusterFolders` option fails

### ISSUE THREAD

**Issue by naddison36** [naddison36/sol2uml#5]
Failure message is `Failed to convert dot to SVG. lost 2 57 edge` when the `Viz(dot)` is run to convert the dot string to a svg.

Removing some of the associations fixes the problem so it looks like `viz.js` library struggles with the size of the generated svg.

**Comment by asaharinna** [comment]
😁

**Comment by Nguyentiensy99** [comment]
Ok

**Comment by BigBlueHundids** [comment]
>.

**Comment by naddison36** [comment]
Fixed with v2.0
