### ISSUE TITLE
Switch from svg-to-png to convert-svg-to-png

### ISSUE THREAD

**Issue by Ancient123** [naddison36/sol2uml#67]
`svg-to-png` is effectively abandoned
  - Hasn't had a release in 4 years
  - Hasn't had a commit to the repo since Dec 13, 2018
  - Depends on [phantomjs-prebuilt which is officially deprecated](https://www.npmjs.com/package/phantomjs-prebuilt)

`convert-svg-to-png`
  - recent releases and commit activity
  - uses puppeteer and chromium which is actively supported

**Comment by naddison36** [comment]
Thanks for raising this. I've replaced `svg-to-png` with `convert-svg-to-png` for Release 2.0.0 which is currently on the `feat/storage` branch. PR is https://github.com/naddison36/sol2uml/pull/73

**Comment by naddison36** [comment]
Done in v2.0.0
