### ISSUE TITLE
viz.js error

### ISSUE THREAD

**Issue by ittayd** [naddison36/sol2uml#70]
When executing with no arguments:
`(node:24148) V8: /usr/local/lib/node_modules/sol2uml/node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use`

**Comment by naddison36** [comment]
This is a warning message from the now deprecated [viz.js](https://github.com/mdaines/viz.js) package. I need to find a npm package to replace viz.js that wraps [Graphviz](https://www.graphviz.org/) for Javascript or ideally TypeScript.

**Comment by naddison36** [comment]
Fixed in v2.0.0 by changing the `viz.js` dependency to `@aduh95/viz.js`
