### ISSUE TITLE
"Failed to find parent contract" error

### ISSUE THREAD

**Issue by tinchoabbate** [naddison36/sol2uml#84]
Hey there!

I was trying to run the `sol2uml storage` command on the `0x72fb5253ad16307b9e773d2a78cac58e309d5ba4` address. But I'm getting an error:

```
sol2uml storage 0x72fb5253ad16307b9e773d2a78cac58e309d5ba4
Failed to generate storage diagram Error: Failed to find parent contract IForwarder of contracts/Voting.sol
```

Spent some time trying to debug but i've hit a dead end. Seems like the contracts are not being parsed correctly? Perhaps this has to do with the fact that it's an old Solidity version ?

Just for context, though I don't think it's related to the specific error, the address contains an implementation contract that's sitting behind the proxy at `0x2e59a20f205bb85a89c53f1936454680651e618e`.

**Comment by naddison36** [comment]
Try the latest version v2.1.1

There was a problem with importing contracts from imported links that I fixed today.

```
sol2uml storage 0x72fb5253ad16307b9e773d2a78cac58e309d5ba4
Generated svg file /Users/nick/Documents/workspaces/sol2uml/Voting.svg
```

**Comment by tinchoabbate** [comment]
yeap, that was it! Thanks for the reply and your work in this tool, super useful 🙌
