### ISSUE TITLE
Feature request: version flag

### ISSUE THREAD

**Issue by engn33r** [naddison36/sol2uml#88]
Could a `-V` or similar flag be added to the CLI tool (and corresponding help text) to quickly check the version of sol2uml installed? I can manually check my package.json file but a flag would be faster.

Edit: I see `npm ls sol2uml -g` is suggested in the README, which is faster than finding the package.json. Still, a `-V` flag would be nice.

**Comment by naddison36** [comment]
The -v option is currently being used for verbose which outputs debug messages. I'll see what other cli's that us commander do.

**Comment by naddison36** [comment]
I've added a `-V --version` option in v2.1.3.

The `-v --verbose` option remains as is.

Thanks for raising.
