### ISSUE TITLE
Feature request: add support for more chains

### ISSUE THREAD

**Issue by engn33r** [naddison36/sol2uml#90]
There are other L1 and L2 chains that could be nice to support in the future, including but not limited to:
- Optimism
- Avalanche
- Solana
- Fantom
- Gnosis
- Cronos

Nice tool, great work :+1:

Edit: there may be an opportunity to borrow code from this project, which also queries the block explorer for contract code https://github.com/SergeKireev/ethereum-sources-downloader

**Comment by naddison36** [comment]
Thanks for raising and providing the link to [ethereum-sources-downloader](https://github.com/SergeKireev/ethereum-sources-downloader).

I've added Avalanche, Crono, Fantom, Moonbeam and Optimistic.
I can't find Etherscan-based versions for Gnosis and Solana so I wasn't able to add those.
